name: Content - Beta Release
on: 
  push:
    branches-ignore:
      - main
jobs:
  dev:
    uses: mkoelle/com.mkoelle/.github/workflows/shared/publish_content.yml@feature/infra-deploy
    with:
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
